### ISSUE TITLE
Chart ID not found

### ISSUE THREAD

**Issue by csomyy** [amargo/appdeamon-scripts#1]
Üdv!
Ajánlás útján találtam meg az EONos scriptet, de a segítségem ellenére is falba ütköztem.
Nem tudom, honnan lehet megtudni a chart_ID nevű változót.
Tudnál segíteni?
Köszi

**Comment by amargo** [comment]
Szia!

A chart_id-t én a response message-ben találtam meg, 
![image](https://user-images.githubusercontent.com/6311107/157002677-39c30d60-71bc-4d69-8f00-94fe5e61088b.png)
Itt a chartData alatt lévő reportId-t kell magadni.
Fontos, hogy az 1.8.0 és 2.8.0 is megfelelő sorrendbe legyen megadva: Ez chart data:
![image](https://user-images.githubusercontent.com/6311107/157002870-522dc474-1813-4365-b5ee-8ac5b6742717.png)

Ez pedig a report:
![image](https://user-images.githubusercontent.com/6311107/157002979-4f0eafd9-0d58-4cfd-9b69-aa35e62cf8a8.png)

(valamiért nem kaptam emailt)
