### ISSUE TITLE
Elakadtam, segíts kérlek!

### ISSUE THREAD

**Issue by csomyy** [amargo/appdeamon-scripts#2]
Üdv!
Újra raktam a HA rendszerem és nem tudom újra felkonfigurálni az eon leolvasó rendszerem.
Elvileg működik, megy alatta a MariaDB, DB kapcsolat van, lát adatokat az eontól, de nem akar beindulni.
Ezzel a loggal megáll.
Merre menjek?
Köszi

2022-06-17 22:51:09.535637 INFO normalized_energy_usage: END - normalize_data
2022-06-17 22:51:09.541924 INFO normalized_energy_usage: START - get_states
2022-06-17 22:51:09.552211 INFO Eon: [{'time': '2022-06-15T00:00:00', 'value': 1305.481, 'status': 0, 'statustext': 'W', 'statusdescription': 'St��tusz: W', 'tariffrateid': None, 'tariffratename': '', 'tariffratehtmlcolor': '', 'novalueforthisperiod': False}, {'time': '2022-06-16T00:00:00', 'value': 1312.183, 'status': 0, 'statustext': 'W', 'statusdescription': 'St��tusz: W', 'tariffrateid': None, 'tariffratename': '', 'tariffratehtmlcolor': '', 'novalueforthisperiod': False}, {'time': '2022-06-17T00:00:00', 'value': 1317.692, 'status': 0, 'statustext': 'W', 'statusdescription': 'St��tusz: W', 'tariffrateid': None, 'tariffratename': '', 'tariffratehtmlcolor': '', 'novalueforthisperiod': False}]
2022-06-17 22:51:09.594409 WARNING AppDaemon: Log formatting error - 'not all arguments converted during string formatting'
2022-06-17 22:51:09.597306 WARNING AppDaemon: message: 2022-06-17 22:51:09.592683, args: ("Error get_report_data local variable 'rows' referenced before assignment.",)
2022-06-17 22:51:09.601293 WARNING AppDaemon: Log formatting error - 'not all arguments converted during string formatting'
2022-06-17 22:51:09.603725 WARNING AppDaemon: message: 2022-06-17 22:51:09.600338, args: ("Error retrive data from local variable 'eon_2_8_0_report' referenced before assignment.",)
2022-06-17 22:51:09.641460 INFO normalized_energy_usage: ERROR - normalize_data
2022-06-17 22:51:09.643854 WARNING AppDaemon: Log formatting error - 'not all arguments converted during string formatting'
2022-06-17 22:51:09.645595 WARNING AppDaemon: message: 2022-06-17 22:51:09.643063, args: ("Error 'NoneType' object is not subscriptable.",)
2022-06-17 22:51:09.649947 INFO normalized_energy_usage: END - normalize_data
2022-06-17 22:51:09.653861 INFO normalized_energy_usage: END - Normalizing energy usage

**Comment by amargo** [comment]
Szia,

Az látszik, hogy a json-t jól leszedi, az ez:
`[
   {
      "time":"2022-06-15T00:00:00",
      "value":1305.481,
      "status":0,
      "statustext":"W",
      "statusdescription":"St��tusz: W",
      "tariffrateid":"None",
      "tariffratename":"",
      "tariffratehtmlcolor":"",
      "novalueforthisperiod":false
   },
   {
      "time":"2022-06-16T00:00:00",
      "value":1312.183,
      "status":0,
      "statustext":"W",
      "statusdescription":"St��tusz: W",
      "tariffrateid":"None",
      "tariffratename":"",
      "tariffratehtmlcolor":"",
      "novalueforthisperiod":false
   },
   {
      "time":"2022-06-17T00:00:00",
      "value":1317.692,
      "status":0,
      "statustext":"W",
      "statusdescription":"St��tusz: W",
      "tariffrateid":"None",
      "tariffratename":"",
      "tariffratehtmlcolor":"",
      "novalueforthisperiod":false
   }
]`

Viszont az is látszik, hogy csak egy mérőd van, azaz 1.8.0-van gondolom beállítva, ezért id dobott több helyen is hibát (ezt majd belerakom, hogy egyértelműbb legyen). Nem tudom, hogy visszatáplálós órád van-e?
Ha igen, akkor kell egy munkaterület, ami így van beállítva:
![image](https://user-images.githubusercontent.com/6311107/175761633-54b065d3-92a4-4261-b161-c7bc722f567f.png)

Mivel az appDeamon-os verzó pedig használja a 15 perces adatokat is, ezért kell ugyan ezen a munkaterületen egy másik megjelenítés is:
![image](https://user-images.githubusercontent.com/6311107/175761679-9f3ed7e4-144a-4a04-8957-98155b65291a.png)

Ha nem visszatáplálós az órád, akkor azt jelenleg nem támogatja a script, de szabadon szerkeszthető :)

**Comment by csomyy** [comment]
Így van beállítva. Sőt! Működött, de a HA frissítése szétrombolta a napelemes integrációmat és újra telepítettem az egész HA-t. Most pedig nem tudom felkonfigurálni a scriptedet a fenti hiba miatt. A eon oldalon nem változott semmi azóta, hogy működött.

**Comment by csomyy** [comment]
![image](https://user-images.githubusercontent.com/85110866/175762148-a424f4df-9492-47e3-b324-936978acf835.png)
![image](https://user-images.githubusercontent.com/85110866/175762157-97e50dcd-0931-427f-9711-e5429a5fb08b.png)

**Comment by csomyy** [comment]
A karakter kódolás nem lehet probléma? "Státusz"

**Comment by amargo** [comment]
Melyik HA frissítés vágta tönkre? Mert olvastam többektől, hogy a 22.6.7-es frissítés másoknál is különböző galibákat okozott.

Viszont, ha volt backup-od, akkor ezeket is lementi, a mostani konfigurációdat eltudnád küldeni (érzékeny adatokat kiszedve).
Most néztem a loggolást, és külön-külön loggolom ki az 1.8.0 és 2.8.0-t: https://github.com/amargo/appdeamon-scripts/blob/8a1fb043bf519b42797bf73c3b6e112009b9d83d/eon/read_eon.py#L122

Majd az látszik, hogy a rows változó nem megfelelő: 
https://github.com/amargo/appdeamon-scripts/blob/8a1fb043bf519b42797bf73c3b6e112009b9d83d/eon/read_eon.py#L148

Ez pedig csak, akkor lehetséges, ha már a korábbi states elérésekor is valami hiba történik (ami nincs lekezelve)
https://github.com/amargo/appdeamon-scripts/blob/8a1fb043bf519b42797bf73c3b6e112009b9d83d/eon/read_eon.py#L255

Nemsokára küldök majd be egy változatot, ahol több hibakeresési lehetőség is van.
De kellene a config fájl, hogy lássam mi van benne.

**Comment by csomyy** [comment]
Köszi az energiádat!

A gond a 2022.4.0 frissítéssel kezdődött. A SolarEdge entitásokat kizárta a HA rossz adatra hivatkozva és az EON script entitásait is. Azt hiszem valami komolyabb adatbázis változás volt a frissítéssel, talán azzal lehet kapcsolatban.
Aztán úgy néz ki, a SolarEdge APIban lehetett valami gond, mert hogy az adott év termelése magasabb értéket mutatott, mint a globális rendszertermelés és ezért dobta el a HA. Részemről nem is lényeges a frissítés, mer vajmi keveset használok a HA rendszeréből. A napelem miatt raktam fel, meg a ház fogyasztását monitorozandó, meg pár ESP hőmérőm van. Épp most gondolkodom, hogy a locsoló rendszert rákötöm, de eléggé low prio.

Eon:
  module: read_eon
  class: Eon
  eon_url: 'https://energia.eon-hungaria.hu/W1000'
  username: 'xxxx@gmail.com'
  password: 'xxxx.'
  report_id: 'xxxx'
  chart_id: 'xxxx'
  #last_reset: "2020-09-14T11:25:00+00:00"
  every_hour: 30
  hyphen: 'xxxx'
  offset: -2
  host: 192.168.1.73
  username_db: eon
  password_db: eon
  database: homeassistant
  1_8_0_sensor: sensor.eon_1_8_0_energy_total
  2_8_0_sensor: sensor.eon_2_8_0_energy_total
  positive_a_energy: sensor.eon_positive_a_energy_power
  negative_a_energy: sensor.eon_negative_a_energy_power



normalized_energy_usage:
  class: NormalizedEnergyUsage
  module: normalized_energy_usage
  host: 192.168.1.73
  username_db: eon
  password_db: eon  
  database: homeassistant
  offset: -2
  numdays: 4
  every_hour: 1
  1_8_0_sensor: sensor.eon_1_8_0_energy_total
  2_8_0_sensor: sensor.eon_2_8_0_energy_total

**Comment by amargo** [comment]
Már világos mi a gond a HA-ban a 22.4.X-es verziótól megváltozott a [DB szerkezete](https://prohardver.hu/tema/okos_otthon_smart_home/hsz_34602-34602.html). Ezzel kapcsolatban került is be ide egy javítás:
https://github.com/amargo/appdeamon-scripts/commit/06a86e50f14ee543d5930dcb2076bd567721f9bf

Viszont javaslom, hogy a mostani utolsó állapotot szedd le, mert a loggolást kicsit átalakítottam, amennyire időmből telt :)

Javaslat:
Mivel akkor most biztosan hiányos az adatbázisod ezért érdemes az eon portálról leszedni régebbi adatokat is ehhez az offset-et kell annyival csökkentei, amikor még voltak értékeid.

**Comment by csomyy** [comment]
Frissítettem az HA-t. Az eon script működik, a solaredge nem ! :/
De ez már fél siker!

**Comment by amargo** [comment]
Akkor ezt zárom, ha nincs több kérdés :)

(Én legalább beállítottam az email értesítést)
